### PR TITLE
Restructure API types for maintainability 

### PR DESCRIPTION
**Pull request by cainthebest**
### What is this?

Due to recent changes a few endpoints have had braking changes or have been "removed" (the endpoints exist and return HTTP 200 but no data). To combat the changes affecting the package I am restructuring the way endpoints are typed to increase the maintainability. Currently I alone actively (when I can) maintain the package and develop it with the odd contribution from those who are kind enough to do so. This branch will not be merged till I feel that it is ready to be in production and meets the needs of the `v0.3.0` milestone requirements. **Production code will not be affected** with these changes as the source is bundled for production so there will not be any breaking changes on the user side.

### CODE REVIEW

**Comment by cainthebest** [comment]
Changed from draft to see if the ci issue was affected by pr being draft

**Comment by infiniwave** [comment]
Suggestion - it's a good idea to squash the commits to make it easier to read

**Comment by cainthebest** [comment]
Development of the restructuring is being put on hold due to issues with the api and uncertainty with responses, when the api issues are resolved development will continue as normal

**Comment by cainthebest** [comment]
docs moved to separate repo 
https://github.com/nitradojs/documentation

**Comment by cainthebest** [comment]
Moving alt format into pr as this seems a better structure

**Pull request merged**
